LIST P=16F877
#INCLUDE <P16F877.INC>
	COUNT EQU	0X20
	CORR	EQU	0X21
	CON1	EQU 0X22
	CON2	EQU 0X23
	CON3	EQU 0X24
	CON4	EQU	0X25
	ORG 00H
	GOTO MAIN
	ORG 04H
	GOTO INT
	ORG 06H
MAIN
	CLRF TMR1H
	CLRF TMR1L
	BSF STATUS,5
	CLRF	TRISB
	BCF		STATUS,5
	MOVLW	b'00001001
;ENABLE TIMER1, INTERNAL CLOCK, IGNORED, OSCILLATOR SHUT OFF, 1:8 PRESCALER
	MOVWF	T1CON
	MOVLW	.15
	MOVWF	COUNT
	MOVLW 	.2
	MOVWF	CON1
	BCF		PIR1,0; LIMPIA BANDERA DE INTERRUPCIÓN DEL TIMER1
		BSF		STATUS,5; CAMBIO DE BANCO
		BSF		PIE1,0; HABILITA LA INTERRUPCIÓN DEL TIMER1, PRIMER NIVEL 
		BCF		STATUS,5;
		BSF		INTCON,6;  HABILITAR LAS INTERRUPCIONES PERIFÉRFICAS, SEGUNDO NIVEL
		BSF		INTCON,7; 	HABILITACIÓN GLOBAL DE INTERRUPCIONES, TERCER NIVEL
	MOVLW	0XFF
	MOVWF	CORR
	MOVWF	PORTB
	BCF	STATUS,0
RETARDO NOP
	GOTO RETARDO	
INT
	MOVLW	0X00
	SUBWF	COUNT,0
	BTFSS  STATUS,2
	GOTO SUBL
	GOTO RET2
SUBL
	DECFSZ COUNT,1
	GOTO UNO
RET2
	DECFSZ	CON1,1
	GOTO TRES	
	GOTO DOS
DOS
	MOVLW .2
	MOVWF	CON1
	MOVLW .15	
	MOVWF	COUNT
	COMF	CORR
	MOVF	CORR,0
	MOVWF	PORTB
UNO
	BCF	PIR1,0
	RETFIE
TRES
	BCF	PIR1,0
	MOVLW B'10111101
	MOVWF	TMR1H
	MOVLW B'11110000
	MOVWF  	TMR1L
	RETFIE

END

