;Utilización del timer0
LIST p=16f877;
TMR0 	EQU 01H
PORTB	EQU	06H
PORTC	EQU	07H
;INTCON	EQU	08H
CUENTA	EQU	20H
#INCLUDE <P16F877.INC>
	ORG 0
	GOTO INICIO
	ORG 5
INICIO	BSF	STATUS, 5
		CLRF	PORTB ;WARNING SE ESTÁ EDITANDO TRISB
		CLRF	PORTC;WARNING SE ESTÁ EDITANDO TRISB 
		MOVLW	B'11010111'
		MOVWF	TMR0; WARNING CARGA EN OPTION REG
		BCF 	STATUS,5
CICLO	CLRF	PORTB 
		CLRF 	PORTC 
		;PRUEBA PUERTO B
		BSF		PORTB,0
CICLOB	CALL RETARDO
		RLF	PORTB,1
		BTFSS	STATUS,0
		GOTO	CICLOB
		;PRUEBA PUERTO C
		BSF	PORTC,0
CICLOC	CALL RETARDO
		RLF PORTC,1
		BTFSS	STATUS,0
		GOTO CICLOC
		GOTO CICLO
		;RUTINA DE RETARDO
RETARDO	CLRF	CUENTA
CICLOR	MOVLW 	01H
		ADDWF	CUENTA,1
		CLRF	TMR0
TIEMPO	BTFSS	INTCON,2
		GOTO	TIEMPO
		BCF		INTCON,2
		MOVLW 	23
		SUBWF	CUENTA
		BTFSS	STATUS,Z
		;TIEMPO TOTAL: 256 (TIEMPO)*256(PRESCALER)*8(CUENTA)
		GOTO	CICLOR
		RETURN
		END