;Configuración del TIMER1
LIST p=16f877
;programa timer 1 y su interrupción
CORR	EQU	20H
CON1	EQU	21H
TEMPO	EQU	22H
#INCLUDE <P16F877.INC>
	ORG		00H
	GOTO 	MAIN
	ORG 	04H; DIRECCIÓN DE INTERRUPCIÓN
	GOTO 	TIMER1
	ORG		06H
MAIN	BSF	STATUS,5
		CLRF	TRISB
		BCF		STATUS,5
		MOVLW	0X31;00110001 
		;ENABLE TIMER1, INTERNAL CLOCK, IGNORED, OSCILLATOR SHUT OFF, 1:8 PRESCALER
		MOVWF	T1CON
		MOVLW	0X0A; 00001010 
		MOVWF	CON1
		BCF		PIR1,0; LIMPIA BANDERA DE INTERRUPCIÓN DEL TIMER1
		BSF		STATUS,5; CAMBIO DE BANCO
		BSF		PIE1,0; HABILITA LA INTERRUPCIÓN DEL TIMER1, PRIMER NIVEL 
		BCF		STATUS,5;
		BSF		INTCON,6;  HABILITAR LAS INTERRUPCIONES PERIFÉRFICAS, SEGUNDO NIVEL
		BSF		INTCON,7; 	HABILITACIÓN GLOBAL DE INTERRUPCIONES, TERCER NIVEL
		MOVLW	0XFF;1111 1111
		MOVWF	CORR;
		MOVWF	PORTB; CORR
		BCF		STATUS,0; BANCO 0
RETARDO	NOP ;EL TIMER SE INCREMENTA CON CICLOS DE INSTRUCCIÓN, LE PUSIMOS UN PRESCALADOR
		GOTO RETARDO; 8*65534 POR EL PRESCALER Y EL TIMER DE 16 BITS
		;RUTINA DE INTERRUPCIÓN
TIMER1
		DECFSZ	CON1,1; 10 VECES
		GOTO UNO
		COMF	CORR; COMPLEMENTO EN F = 0X00
		MOVF	CORR,0; 
		MOVWF	PORTB; DESPLIEGA CEROS 
UNO		BCF	PIR1,0 ;BAJAR LA BANDERA
		RETFIE; REGRESO DE INTERRUPCIÓN
		END
		
	